<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>radio_choice</name>
   <tag></tag>
   <elementGuidId>1c1a94d7-1139-465d-9ccb-7749ef5f3eb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//p[text()='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//p[text()='${text}']</value>
   </webElementProperties>
</WebElementEntity>
